---
kind: pipeline
type: docker
name: default

steps:
- name: update
  image: alpine/git
  commands:
    - cd /var/docker/saca-stats
    - git pull
  volumes:
    - name: docker-dir
      path: /var/docker

- name: redeploy
  image: docker/compose:1.24.1
  commands:
  - cd /var/docker/saca-stats
  - docker-compose stop saca-stats
  - docker-compose up -d saca-stats
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
  - name: docker-dir
    path: /var/docker

volumes:
- name: docker-socker
  host:
    path: /var/run/docker.sock
- name: docker-dir
  host:
    path: /var/docker
