---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker
  commands:
  - cd /var/docker
  - ls
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
  - name: docker-dir
      path: /var/docker

volumes:
- name: docker-socker
  host:
    path: /var/run/docker.sock
- name: docker-dir
  host:
    path: /var/docker
