---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker
  commands:
  - ls
  - "echo ${DOCKER_COMPOSE_YAML_DIR}"
  - env
  secrets:
  - DOCKER_COMPOSE_YAML_DIR
  volumes:
  - name: docker
    path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
- name: docker-compose
  host:
    path: ${DOCKER_COMPOSE_YAML_DIR}
