---
kind: pipeline
type: docker
name: default

steps:
- name: build:
  image: docker
  commands:
  - ls
  - cd /docker-dir
  - ls
  secrets:
  - DOCKER_COMPOSE_YAML_DIR
  volumes:
  - name: docker
    path: /var/run/docker.sock
  - name: docker-compose
    path: /docker-dir

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
- name: docker-compose
  host:
    path: ${DOCKER_COMPOSE_YAML_DIR}
