---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker
  commands:
  - ls
  - echo ${DOCKER_COMPOSE_YAML_DIR}
  - cd /docker
  - ls
  secrets: [ DOCKER_COMPOSE_YAML_DIR ]
  settings:
    DOCKER_COMPOSE_YAML_DIR:
      from_secret: DOCKER_COMPOSE_YAML_DIR
  environment:
    DOCKER_COMPOSE_YAML_DIR:
      from_secret: DOCKER_COMPOSE_YAML_DIR
  volumes:
  - name: docker
    path: /var/run/docker.sock
  - name: docker-compose
    path: /docker

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
- name: docker-compose
  host:
    path: $${DOCKER_COMPOSE_YAML_DIR}
