version: 2.0

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t docker.jkbff.com/saca-stats:latest .
          docker push docker.jkbff.com/saca-stats:latest

  deploy:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: /app
    steps:
      - setup_remote_docker
      - run: |
          mkdir config
          echo $KUBE_CONFIG | base64 -d > /app/config/config
          docker run -v /app/config:/config bitnami/kubectl:1.15.3 get pods --all-namespaces

workflows:
  version: 2
  build_and_deploy:
    jobs:
      #- build
      - deploy
          #requires:
          #  - build
