version: 2.0

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t docker.jkbff.com/saca-stats:latest .
          docker push docker.jkbff.com/saca-stats:latest
  deploy:
    docker:
      - image: alpine
    steps:
      - run: echo "hi"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
